name: xayn_architecture
description: Xayn's Flutter architecture
version: 1.0.0
homepage: https://www.xayn.com/
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^7.3.1
  hydrated_bloc: ^7.1.0
  logger: ^1.0.0
  path_provider: ^2.0.5
  provider: ^6.0.1
  rxdart: ^0.27.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.3.0
  flutter_lints: ^1.0.4
  pedantic: ^1.9.0
