name: xayn_architecture
description: Xayn's Flutter architecture
version: 1.0.0
homepage: https://www.xayn.com/
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  envify: ^2.0.0
  equatable: ^2.0.3
  get_it: ^7.0.0
  injectable: ^1.2.2
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  flutter_bloc: ^7.3.1
  hydrated_bloc: ^7.1.0
  logger: ^1.0.0
  path_provider: ^2.0.5
  provider: ^6.0.1
  rxdart: ^0.27.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.3.0
  build_runner: ^2.1.4
  envify_generator: ^2.0.2
  flutter_lints: ^1.0.4
  # Just used here for the example project, but freezed should not be used for the lib.
  freezed: ^0.15.0
  injectable_generator: ^1.5.2
  pedantic: ^1.9.0
