name: Post merge checks

env:
  FLUTTER_VERSION: "2.5.2"

on:
  push:
    branches:
      - main

jobs:
  Basic-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Write .env.dev file
        working-directory: ./example
        run: |
          cat <<EOT >> .env.dev
          SEARCH_API_BASE_URL="api-gw.xaynet.dev"
          SEARCH_API_SECRET_KEY=""
          IMAGE_FETCHER_URL="https://img-fetcher.xaynet.dev"
          EOT

      - name: Get Packages
        run: |
          flutter pub get

      - name: Run build_runner
        run: |
          cd example
          flutter pub run build_runner build --delete-conflicting-outputs
          cd -
      - name: Flutter format
        run: |
          flutter format ./ --set-exit-if-changed
      - name: Flutter Analyze
        run: |
          flutter analyze lib test
      - name: Run Tests
        run: |
          flutter test
